spring:
  application:
    name: Config-Default
eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
#by using this http://localhost:8761/eureka inorder to register with the sever
    service-url:
      defaultZone: http://localhost:8761/eureka
